### ISSUE TITLE
Improve Node loading time

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scripting#32]
The node slows down the loading time of KNIME, by slowing down the loading time of any workflow containing it.

**Comment by gab1one** [comment]
The node loading time is still slower than most nodes but not a big problem anymore.

**Comment by dietzc** [comment]
anyway, the script should not be compiled so often an we should avoid too many contexts.

**Comment by gab1one** [comment]
There is only one context per node now and the compilations are reduced quite a bit. Node loading time is no longer an issue.
