### ISSUE TITLE
Context handling in Scripting Node

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip-scripting#46]
At the moment, `NodeDialog` and `NodeModel` have their own contexts and additionally many stateless Services are recreated for each `ScriptingNode` twice.

Following suggestions to handle this issue:

* We could speed-up the `Context` creation in general on SciJava side (@ctrueden :-))
* We have to think about only creating a single `Context` for each `ScriptingNode`. This implies that we have to create explicit `NodeSettingsService` for `NodeDialog` and `NodeModel` e.g. `NodeDialogNodeSettingsService` and `NodeModelNodeSettingsService` which are then used in `KNIMEWidgetModelService` (dialog) and `NodeSettingsHarvester` (model). Both can inherit from a single `AbstractNodeSettingsService` class. This is required as `NodeModel` and `NodeDialog` _have to_ maintain their own instances of `SettingsModel`s.

**Comment by ctrueden** [comment]
I've been talking to @gab1one quite a bit about this lately. He is currently working on a couple of possible strategies:

* Use a single `Context` for everything, with services intelligent enough to dish out their state on a per-node basis as needed, using `WeakHashMap` and/or `ThreadLocal` etc.
* Use a thin `Context` subclass wrapper around the main context, to creating any more "full-blown" contexts. I guess this latter strategy is what @gab1one and @dietzc are currently leaning toward, although I still prefer the single `Context` approach.

**Comment by gab1one** [comment]
So currently there is one thin context created per Node (shared by Dialog and NodeModel).
It is wrapping the global Scijava Context transparently. [take a look.](https://github.com/knime-ip/knip-scijava/blob/settingsServiceRefactor/org.knime.scijava.core/src/org/knime/scijava/core/DelegateableContext.java)

**Comment by dietzc** [comment]
Here is why I prefer single the solution of @gab1one at the moment:

KNIME nodes don't have all information about their states They know when they are configured, executed and resetted, but they don't know for example when they are removed by the framework. Furthermore, the framework may internally create instances of nodes, which are not displayed in the UI or executed somewhere else etc. So a KNIME node should always be self-contained and from the outside no other class should have a reference on the node (besides the KNIME framework).

So, if we would have a global context, we would have to somehow take care about the house-keeping of the nodes and we would start keeping references on these nodes (even if they are weak). So from my feeling this will bite us at some point and I prefer to stick to a local `Context` which reaches out to the global one if necessary.

**Comment by ctrueden** [comment]
Fair enough, and make sense. If it works, great.

@gab1one Once the delegating context is tested and working, I'd be happy to add it to scijava-common core as `CustomContext` (analogous to how Ops has `CustomOpEnvironment`).

**Comment by gab1one** [comment]
I am not sure ``CustomContext`` is a good name for it, as it still requires a super context, maybe ``SubContext`` is more appropriate ?

**Comment by ctrueden** [comment]
Oh sure, I like `SubContext`.
