### ISSUE TITLE
Inconsitency with SettingModels

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip-scripting#57]
If you add an image input manually, i.e. not using the UI for the mapping, a NPE is thrown on `Apply`. Should be solved with https://github.com/knime-ip/knip-scripting/issues/48 and https://github.com/knime-ip/knip-scripting/issues/45. Please double-check.

**Comment by gab1one** [comment]
We need to generate the mappings for manual inputs.

**Comment by gab1one** [comment]
No longer applicable with the new mode
