### ISSUE TITLE
Be inspired be UI of JavaSnippet Node

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip-scripting#58]
The JavaSnippet Node in KNIME has all the functionality working we need for proper development in a scripting node: 

* working code-completion
* auto-imports
* compile error hiliting

Let's see if we can make that happen in our node/ij2, too.

**Comment by Squareys** [comment]
> working code-completion

Does Code completion not work anymore?

**Comment by dietzc** [comment]
it does, but limited. e.g. you can run it on `OpService` directly or even nested classes are not possible.

**Comment by Squareys** [comment]
There is a `depth` option somewhere in RSTALanguageSupport/JavaLanguageSupport, I think. I think that could be what you are looking for.

**Comment by dietzc** [comment]
where to set it?

**Comment by dietzc** [comment]
code will be refactored.
