### ISSUE TITLE
Save / Export of script code

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scripting#60]
The user should be able to save the code written into the Scripting Node to an external file, this behavior is provided by other KNIME Scripting Nodes, e.g. Java Snippet.

- [ ] Pressing ``Ctrl + S`` opens save dialog.

**Comment by Squareys** [comment]
Doesn't it already do that automatically because of RSyntaxTextArea? Try it please ;)
If you allow exporting the script, I think you should allow importing scripts aswell.

**Comment by gab1one** [comment]
Oh it does, it just uses ``Ctrl + S`` on OSX instead of the ``CMD + S`` I expected.

I am not sure about importing as it would be different from every other scripting node, but it is worth considering.
