### ISSUE TITLE
Fix calling ops in Javascript scripts

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scripting#66]
Javascript scripts don't support calls to  OpService which is **very bad**. This needs to be fixed.

It fails to [lookup the class in the script service](
https://github.com/scijava/scijava-common/blob/master/src/main/java/org/scijava/script/DefaultScriptService.java#L255).
Indicating a problem with the

**Comment by hinerm** [comment]
:+1: for using the latest version of components. You can certainly use an `OpService` in a JS script in Fiji right now.

As a side thought, are you doing anything fancy with your context creation?

**Comment by gab1one** [comment]
I am using the latest versions, just seems like the code engine wants to create regular inputs out of calls like ``@OpService ops`` ...

**Comment by gab1one** [comment]
Fixed by partially preprocessing the modules before generating the dialog.
