### ISSUE TITLE
Stop scijava-scripting from adding aditional parameters to scripts

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scripting#78]
The scijava scripting framework adds an additional result element to each
script, it is named "result" and it's value is the return value  the latest
statement executed in the script.

This is highly anoying and workarounds will always be hacks. We need to fix this upstream.

**Comment by ctrueden** [comment]
We do have a plan for fixing this. If you cannot find the relevant issue
let me know and I will look it up.

**Comment by dietzc** [comment]
I actually couldn't find the issue @ctrueden. can you have a look?

**Comment by ctrueden** [comment]
I couldn't find the relevant issue either. So I just went ahead and fixed it: scijava/scijava-common#242. Hopefully that is a reasonable compromise. Technically it breaks backwards compatibility, but only for edge cases IMHO.

**Comment by dietzc** [comment]
thanks @ctrueden!
