### ISSUE TITLE
Switch to Dialog button sometimes opens dialog instead of compilation errors

### ISSUE THREAD

**Issue by stelfrich** [knime-ip/knip-scripting#85]
The _Switch to Dialog_ button shows not deterministic behavior when compilation errors are in the script. Instead of showing log of the compilation it shows the dialog for setting parameters.

**Comment by gab1one** [comment]
In which programming language did these errors occur?

In the supported languages other than java most compilation errors can only be detected at run-time.

**Comment by stelfrich** [comment]
> In which programming language did these errors occur?

Java

**Comment by gab1one** [comment]
Found the error in the code caching
.
