### ISSUE TITLE
Select output celltype in the scripting node ui

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scripting#90]
Users might want to select the type of the cell created for a script result explicitly. E.g what kind of numeric cell is used.

We need to have a way to set this in a script (via an ``@Parameter `` anotation ``) 
and via the gui of the scripting node.

**Comment by dietzc** [comment]
related to https://github.com/knime-ip/knip-scripting/issues/82

**Comment by dietzc** [comment]
will be solved in knip-scijava
